### ISSUE TITLE
Possible erreur sur le formatage des dates

### ISSUE THREAD

**Issue by razvn** [davidy4ng/attestation-covid#3]
Dans DateFormatterUtils tu utilises `YYYY` pour le formatage de l'année or, [d'après la doc](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1)
> A common mistake is to use YYYY. yyyy specifies the calendar year whereas YYYY specifies the year (of “Week of Year”), used in the ISO year-week calendar. In most cases, yyyy and YYYY yield the same number, however they may be different. Typically you should use the calendar year.

**Comment by davidy4ng** [comment]
Tout à fait, je fais tout le temps l'erreur à vrai dire :) Merci pour le fix
